---
- name: Install required packages
  openbsd_pkg:
    name:
      - bash
      - bash-completion
      - curl
      - coreutils
      - findutils
      - gawk
      - ggrep
      - git
      - gmake
      - go-1.25.1
      - gsed
      - gtar-1.35p1
      - illumos-os-tests
      - rsync-3.4.1
      - vim-9.1.1265-no_x11
      - wget
    state: present

- name: Add ports collection
  shell: git clone --depth 1 --branch master https://github.com/openbsd/ports /usr/ports
  args:
    creates: /usr/ports

#- name: Add ports collection
#  git:
#    repo: https://github.com/openbsd/ports
#    dest: /usr/ports
#    depth: 1
