---
- name: Install required packages
  openbsd_pkg:
    name:
      - bash
      - bash-completion
      - curl
      - coreutils
      - findutils
      - gawk
      - ggrep
      - git
      - gmake
      - gnupg
      - gsed
      - gtar-1.35
      - mc
      - nmap
      - python3
      - reposync
      - rsync-3.2.7p1
      - screen-4.9.1
      - vim-9.1.139-no_x11
      - wget
    state: present

- name: Add bash completion to git
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: /usr/local/share/bash-completion/completions/git

- name: Add ports collection
  shell: git clone --depth 1 --branch master https://github.com/openbsd/ports /usr/ports
  args:
    creates: /usr/ports

#- name: Add ports collection
#  git:
#    repo: https://github.com/openbsd/ports
#    dest: /usr/ports
#    depth: 1
