---
- name: Configure secure level
  copy:
    src: rc.securelevel
    dest: /etc/rc.securelevel
    owner: root
    group: wheel
    mode: 0600

# NOTE: We can't use Ansible's sysctl module
- name: Security sysctls
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - line: kern.allowkmem=1
      regexp: ^kern\.allowkmem=
    - line: hw.smt=1
      regexp: ^hw\.smt=

- name: Configure doas
  copy:
    src: doas.conf
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: 0600

- name: Create /etc/sudoers.d directory with mode 750
  file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: wheel
    mode: '0750'

- name: Include /etc/sudoers.d
  lineinfile:
    path: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    regexp: '^(#|@)includedir /etc/sudoers.d'
    insertafter: EOF

- name: Configure sudo
  copy:
    src: sudoers.d/custom
    dest: /etc/sudoers.d/custom
    owner: root
    group: wheel
    mode: 0600
