---
- name: Add src collection
  shell: git clone --depth 1 --branch master https://github.com/openbsd/src /usr/src
  args:
    creates: /usr/src
  tags: ['src']

#- name: Add src collection
#  git:
#    repo: https://github.com/openbsd/src
#    dest: /usr/src
#    depth: 1
#    version: master
#  tags: ['src']

- name: Copy /etc/mk.conf
  copy:
    src: mk.conf
    dest: /etc/mk.conf
    owner: root
    group: wheel
    mode: 0644
  tags: ['src']

- name: Copy CUSTOM kernel configuration
  copy:
    src: CUSTOM
    dest: /usr/src/sys/arch/amd64/conf/CUSTOM
#    owner: root
#    group: wheel
    mode: 0644
  tags: ['src']
