---
- name: Add user to needed groups
  user:
    name: "{{ target_user }}"
    groups: wheel,wsrc,wobj
    append: yes
    shell: /usr/local/bin/bash

- name: Fix HOME permissions
  file:
    path: "/home/{{ target_user }}"
    state: directory
    owner: "{{ target_user }}"
    mode: '0700'
